18 elog click
timjon/group4 pull request #23
Opened 2017-11-13 08:54 UTC by pontuslaestadius

2017-11-13 09:15 UTC, IsabelleTornqvist commented on Application/src/visuals/Draw.java
> +     * Resets all the static to be current not static time line. It's the darkest time line.
darkest time line?

2017-11-13 09:15 UTC, IsabelleTornqvist commented on Application/src/visuals/ExecutionLog.java
> +                ((ObservableValue<? extends String> observable, String oldValue, String newValue) -> {
Don't know what this means, can't give feedback on this line

2017-11-13 11:00 UTC, ghost requested changes
shouldn't the logic handle resetting the offset when you click the back button to the previous step?

2017-11-13 11:00 UTC, Rashadse commented on Application/src/visuals/ExecutionLog.java
> +import com.sun.xml.internal.ws.policy.privateutil.PolicyUtils;
what does this do?

2017-11-13 11:11 UTC, Rashadse commented on Application/src/visuals/ExecutionLog.java
> +import javafx.beans.value.ChangeListener;
unused

2017-11-13 11:11 UTC, Rashadse commented on Application/src/visuals/ExecutionLog.java
> +import visuals.handlers.Resizer;
unused

2017-11-13 12:32 UTC, ghost approved these changes

2017-11-13 15:29 UTC, timjon requested changes
I cant click on the latest message to replay it

2017-11-13 15:31 UTC, pontuslaestadius commented
@timjon That's intentional

2017-11-14 08:18 UTC, kosara-g reviewed
Sick dragon bro speed. Nice work overall. I have a few questions: why does it show a black border around the path of the dragon bro sometimes and how do I stop it from looping the message I'm replaying? Other than that, seems great.

2017-11-14 09:57 UTC, kosara-g approved these changes

2017-11-14 11:49 UTC, IsabelleTornqvist approved these changes

2017-11-14 12:21 UTC, timjon requested changes
I found 4 bugs in the 30 seconds I checked the feature so im going to block this

2017-11-15 10:17 UTC, timjon requested changes
1. the previous button replays the message before the one you removed. how do reproduce:
- Import a diagram with at least 4 messages
- Play through the first 3 messages
- Click on the previous button
- The dragon for message number 2 will now fly again
2. Clicking on a message in the execution log and then the last message in the execution log will make the next button animate the same message twice. 
How to reproduce:
- Import a diagram with at least 3 messages
- Simulate the first two messages
- Click on the first message to animate it again
- Click on the second message to animate it again
- Click on the next message button
- The dragon will now fly twice

2017-11-15 11:58 UTC, ghost requested changes
Automation button doesn't work after you latest commit

2017-11-15 12:25 UTC, gusgolko commented
The animation stopped after 1 message for me and then none of the buttons worked but it didn't crash either.

2017-11-15 13:50 UTC, timjon approved these changes

2017-11-15 13:54 UTC, ghost approved these changes

2017-11-15 13:58 UTC, Sebastian-Fransson approved these changes
Auto seems to work now

2017-11-15 14:26 UTC, merged