16 trail
timjon/group4 pull request #29
Opened 2017-11-14 11:03 UTC by IsabelleTornqvist

Trail for message

2017-11-14 11:11 UTC, Rashadse commented on Application/src/visuals/Message.java
> + * @version 2.0
version 1.1?

2017-11-14 11:13 UTC, ghost approved these changes

2017-11-14 11:31 UTC, timjon requested changes

2017-11-14 11:31 UTC, timjon commented on Application/src/visuals/Message.java
> +    private static Image smoke = new Image("resources/cloud1.png");
Should it be called trailed or something else for clarity

2017-11-14 11:31 UTC, timjon commented on Application/src/visuals/Message.java
> +
Removed this since its commented out anyway?

2017-11-14 11:31 UTC, timjon commented on Application/src/visuals/Message.java
> +        //Draw trail for message, for each instance in the arraylist
for THE message?

2017-11-14 11:31 UTC, timjon commented on Application/src/visuals/Trail.java
> +    public double getHeight(){return height;}
Missing some comments for the methods here

2017-11-14 11:50 UTC, IsabelleTornqvist commented on Application/src/visuals/Message.java
> + * @version 2.0
new feature makes it 2.0

2017-11-14 12:40 UTC, timjon requested changes
The trail does not scale with the application
And do we want javadoc comments for methods?

2017-11-15 01:32 UTC, Rashadse commented on Application/src/visuals/Trail.java
> +     * Getter method for getting the height od the trail image
of*

2017-11-15 08:31 UTC, pontuslaestadius commented on Application/src/visuals/Trail.java
> + * Class for the trail of the message
Don't make the header dependable on another class. Just say what this class does, not what it's currently implemented in.Basically make it more generic, and remove mention of message.

2017-11-15 08:51 UTC, pontuslaestadius approved these changes
Added scaling on defect backlog

2017-11-15 09:46 UTC, timjon approved these changes

2017-11-15 09:47 UTC, merged