40 Split view
timjon/group4 pull request #34
Opened 2017-11-22 15:31 UTC by pontuslaestadius

2017-11-22 15:35 UTC, Rashadse commented on Application/src/view/DiagramView.java
> +import jdk.nashorn.internal.runtime.regexp.joni.exception.ValueException;
this line is preventing compilation

2017-11-22 15:43 UTC, ghost approved these changes

2017-11-22 15:59 UTC, timjon requested changes

2017-11-22 15:59 UTC, timjon commented on Application/src/model/Menu.java
> +
Comments on line 219-244 plz

2017-11-22 16:37 UTC, pontuslaestadius commented on Application/src/model/Menu.java
> +
Added

2017-11-22 17:26 UTC, kosara-g approved these changes
Don't forget to remove the test code in Draw when we've merged the class diagram class and the like.

2017-11-23 08:05 UTC, timjon commented
Does not work with the tabs

2017-11-23 11:42 UTC, timjon approved these changes

2017-11-23 11:43 UTC, merged