19 screens
timjon/group4 pull request #37
Opened 2017-11-27 20:07 UTC by gusgolko

User story 19 implemented. New features:
* Welcome screen on startup (scales with application).
* Only import button is enabled on startup.
* Game over screen when the simulation is finished (scales with application).
* Game over screen works with stepping back and forth in the simulation.

2017-11-27 20:58 UTC, ghost approved these changes
stuff is legit af

2017-11-28 09:21 UTC, pontuslaestadius commented on Application/src/model/Menu.java
> +            Draw.removeGameOver();  // Removes the game over screen from the canvas.
This assumes that you can go back. Should this action be in the decode?

2017-11-28 09:23 UTC, pontuslaestadius commented on Application/src/view/visuals/Draw.java
> +        else {
Else not required since if statement breaks flow.

2017-11-28 13:08 UTC, IsabelleTornqvist commented on Application/src/view/visuals/Draw.java
> + * @version 1.5
two version tags

2017-11-28 13:34 UTC, timjon requested changes
Does not work with tabs

2017-11-29 06:26 UTC, gusgolko commented
Closed due to lack of time. Will open a new pull request with working feature.

2017-11-29 06:26 UTC, closed without merging