36 changes class diagram
timjon/group4 pull request #46
Opened 2017-12-06 12:25 UTC by IsabelleTornqvist

User story 36, extended tasks. 
- Change of images for classes in classDiagram (from islands to castles) in accordance to customer request.
- Class diagram structured in matrix formation
- Class names placing. Now placed above image.

2017-12-06 13:15 UTC, gusgolko commented
Well, there aren't any classes to test this yet; does it work with the mock classes from before?

2017-12-06 13:46 UTC, IsabelleTornqvist commented
@gusgolko  Yes it should work the same. I removed the mock data since it shouldn't be apart of the pull request

2017-12-06 14:49 UTC, pontuslaestadius requested changes
Improved Y position suggestions.

2017-12-06 14:49 UTC, pontuslaestadius commented on Application/src/view/visuals/Draw.java
> +        int col = 3; //The "up to" -number of columns in the matrix, counting from 0.
Relocate this higher up so it can be used for other equations

2017-12-06 14:49 UTC, pontuslaestadius commented on Application/src/view/visuals/Draw.java
> +        int space = ((int) this.canvas_class.getWidth()) / this.allClassDiagramClasses.size();
Use the column size to determine the space e.g. 
int space = ((int) this.canvas_class.getWidth()) / (this.allClassDiagramClasses.size()/col);

2017-12-06 14:49 UTC, pontuslaestadius commented on Application/src/view/visuals/Draw.java
> +
use the same Y for both of the cases. e.g.
int y = (int) ((this.canvas_class.getHeight() / (allClassDiagramClasses.size()/(col))));

Then just in the for loop for rows you have y*r.

2017-12-06 14:49 UTC, pontuslaestadius commented on Application/src/view/visuals/Draw.java
> +                allClassDiagramClasses.get(c).place(new Coordinates(x, y), (space) / 2);
Take the size in to account for Y placement. Such that y+space/2. Applies for both places this is done.

2017-12-06 15:23 UTC, pontuslaestadius requested changes
A few bugs came up from my requests. No biggie but needs to be handled.

Only shows full column of classes.
I.e mock 10 of them, you will only see 9.

If you have less classes then N < col you will get a divide by 0.
line 300.
For small amounts of classes the castles overlap each other. (size issue I think)

2017-12-06 15:34 UTC, Rashadse commented
How possible is it to make the classes more spread out through the canvas? there will be more place for the relationships to not look like spaghetti

2017-12-06 15:49 UTC, IsabelleTornqvist commented
Changes were removed due to bugs that came up when applying suggested changes

2017-12-06 15:51 UTC, IsabelleTornqvist commented
@Rashadse If you checked the version that had Pontus' suggested changes, please check this version and see if it's better. Otherwise, yes it would be possible for them to be more spread out, but with scaling, the images would become smaller.

2017-12-07 11:21 UTC, ghost submitted a review, later dismissed
we need to discuss spreading out the classes through the canvas

2017-12-07 14:21 UTC, pontuslaestadius approved these changes
looks good

2017-12-07 14:26 UTC, kosara-g approved these changes
tested manually, works fine; I have no issues with the code changes, well done!

2017-12-07 14:30 UTC, merged