Fixes the parser to work with test cases provided
timjon/group4 pull request #49
Opened 2017-12-11 08:49 UTC by pontuslaestadius

2017-12-11 09:09 UTC, IsabelleTornqvist commented on Server/src/diagramcoordinator.erl
> +	% Checks if there is a valid pid provided.o
.o? Other than that, code looks good from what I can see. Haven't had the time to test it yet though, will do that as soon as possible

2017-12-11 13:57 UTC, timjon requested changes
The parsing does not work for test2.json, test3.json and test5.json

The parsing goes through but everything doesnt get parsed so some parts of the information disapears

2017-12-11 19:00 UTC, ghost approved these changes
Nice! you might as well move the diagram checker defect in the defect backlog to resolved :D

2017-12-13 15:12 UTC, pontuslaestadius commented
Not going to be implemented.

2017-12-13 15:12 UTC, closed without merging